import { ThemeCustomization } from '@/themes'
import { Inter } from 'next/font/google'

import Header from '@/components/shared/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Thoriq Dharmawan | Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ThemeCustomization>
          {children}
        </ThemeCustomization>
      </body>
    </html>
  )
}
